import { useEffect, useState } from 'react'
import { getRandomFact } from './services/facts.js'
import { useCatImage } from './hooks/useCatImage.js'
import { useCatFat } from './hooks/useCatFact.js'
import './App.css'

// const CAT_ENDPOINT_IMAGE_URL = `https://catas.com/cat/says/${firstWord}?size=50&color=red&json=true`

export function App () {
  // const [fact, setFact] = useState('lorem ipsumcat fact whatever')
  // const [fact, setFact] = useState()
  const { fact, refreshFact } = useCatFat()
  const { imageUrl } = useCatImage({ fact })

  /* useEffect(() => {
    getRandomFact()
      .then(fact => setFact(fact))
  }, []) */

  /* useEffect(() => {
    if (!fact) return

    const firstThreeWords = fact.split(' ').slice(0, 3).join(' ')

    fetch('https://api.thecatapi.com/v1/images/search')
      .then(res => res.json())
      .then(response => {
        const { url } = response[0]
        console.log(url)
        setImage(url)
      })
  }, [fact]) */

  /* function handleClick () {
    getRandomFact()
      .then(fact => setFact(fact))
  } */

  function handleClick () {
    refreshFact()
  }

  return (
    <main>
      <h1>App de gatitos</h1>
      <button onClick={() => handleClick()}>Get a new fact</button>
      <section>
        {fact && <p>{fact}</p>}
        {imageUrl && <img src={`${imageUrl}`} alt={`image generated by the three first words of ${fact}`} />}
      </section>
    </main>
  )
}
